name: muse_xlm17
pretrained_path: FacebookAI/xlm-mlm-17-1280
data_root: ../dicts/muse
train_path_template: "{src}_{tgt}_train.txt"
test_path_template: "{src}_{tgt}_test.txt"
pairs:
  - [en, es]
  - [en, ar]
  - [en, zh]
  - [en, de]
  - [en, fr]
template_language: en
prediction_token: "<special1>"
source_pad_token: "<special1>"
padding_token: "<pad>"
num_prediction_tokens: 4
max_length: 20
epochs: 5
lr: 2.0e-5
batch_size: 64
num_workers: 1
seed: 42
lowercase: true
ignore_identical_train_pairs: true
max_tokenized_word_length: 4
output_dir: outputs/muse_xlm17
